DefInjected/PawnKindDef/PawnKinds_Pirate.xml
DefInjected/TaleDef/Tales_Incident.xml

Ao traduzir Tales_Incident.xml reparei que algumas paralvras estavam escritas juntas, não sei se isso era de propósito ou não, então eu alterei, mas qualquer coisa depois eu posso refazer sem alterar as palavras juntas.

Traduções em Tales_Incident.xml

---

DefInjected/GameConditionDef/GameConditions_Misc.xml
DefInjected/MainButtonDef/MainButtons.xml
DefInjected/MentalStateDef/MentalStates_Mood.xml
DefInjected/RecipeDef/ImpliedDefs.xml
DefInjected/TaleDef/Tales_Caravan.xml
DefInjected/TaleDef/Tales_DoublePawn_Relationships.xml
DefInjected/ThingCategoryDef/ThingCategories.xml
DefInjected/ThingDef/Buildings_Misc.xml
DefInjected/ThingDef/Buildings_Ship.xml
DefInjected/ThingDef/ImpliedDefs.xml
DefInjected/ThingDef/Races_Animal_Rodentlike.xml
DefInjected/ThingDef/Races_Animal_Temperate.xml
DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
DefInjected/ThoughtDef/Thoughts_Situation_Social.xml
DefInjected/TraitDef/Traits_Spectrum.xml
DefInjected/TransferableSorterDef/TransferableSorters.xml
Keyed/Dialogs_Various.xml
Keyed/Incidents.xml
Keyed/Letters.xml
Keyed/Messages.xml

patch note
- erro grave, ataque de cólera estava muito fora de contexto e errado (estranhamente aparece como traducao no google translate, pode ter sido isso)
- insult pode ser traduzido pra xingamento (inves de insulto) e trazer coisas regionais
- pigging out, é mais usado comeria um boi inteiro e guloso
- mais substitutos do is no longer

fix erro grave ataque de colera -> irritado e localizacao em insulto

---

DefInjected/IncidentDef/Incidents_Map_Misc.xml
Keyed/Dates.xml
Keyed/Letters.xml
Keyed/Time.xml

Galera, algo que sempre pecamos na tradução foi 'quadrum' e acredito que trimestre seria um termo legal para isso, o que vocês acham? @Firty @RafaelReifel

quadrum > trimestre

---

Core/Backstories/Backstories.xml
Royalty/DefInjected/RoyalTitlePermitDef/RoyalPermits_Empire.xml
Royalty/DefInjected/ThingDef/Apparel_Packs.xml
Royalty/DefInjected/ThingDef/Apparel_Psychic.xml
Royalty/DefInjected/ThingDef/Buildings_Exotic.xml
Royalty/DefInjected/ThingDef/Buildings_Mech.xml
Royalty/DefInjected/WeaponTraitDef/WeaponTraitDefs.xml

I was testing and saw few cheap fixes :smiley: 
Cheers !

Fix few typos.

---

Ideology/Designators.xml
Ideology/Misc_Gameplay.xml

Misc_Gameplay.xml parcialmente traduzido.
OBS.: Não consegui adicionar os arquivos dentro da pasta "Keyed" ( Sou novo na plataforma :-) )

Misc_Gameplay.Xml parcialmente traduzido

---

Ideology/Keyed/FloatMenu.xml
Ideology/Keyed/MainTabs.xml
Ideology/Keyed/Menus_Main.xml
Ideology/Keyed/Messages.xml
Ideology/Keyed/Misc_Gameplay.xml

Misc_Gameplay.XML: quase toda traduzida (70%)
Messages.XML: Quase totalmente traduzido (cerca de 90%)
Fiquem à vontade para fazer considerações e correções!

Tradução:  Misc_Gameplay & Messages

---

Ideology/Keyed/Alerts.xml
Ideology/Keyed/Dialogs_Various.xml
Ideology/Keyed/FloatMenu.xml
Ideology/Keyed/Misc_Gameplay.xml

Terminei algumas traduções XML da pasta keyed

Atualizações Keyed

---

Ideology/DefInjected/IssueDef/Precepts_Transhumanism.xml
Ideology/Keyed/Misc_Gameplay.xml

Apenas corrige erros relacionados com o bioescultor.

Bug Correction - Biosculpter

---

Core/Backstories/Backstories.xml
Core/DefInjected/QuestScriptDef/Scripts_JoinerThreatCore.xml
Core/DefInjected/StatDef/Stats_Basics_General.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
Core/DefInjected/WorkTypeDef/WorkTypes.xml
Core/Keyed/FloatMenu.xml
Core/Keyed/Messages.xml

Esse Pull Request visa atualizar a tradução para a versão 1.3.3087 do RimWorld.
**NOTA AOS REVISORES E TRADUTORES**: Esse Pull Request tem origem de uma branch **desse repositório**, portanto, qualquer membro da equipe está convidado e autorizado a melhorar a tradução deste PR sem restrição. Caso tenham dúvidas com relação a isso, não exitem em me contactar no discord ou pelos comentários desse PR (mas deem preferências ao discord, por favor).

Atualização 1.3.3087

---

Core/DefInjected/StatDef/Stats_Pawns_Combat.xml
Core/DefInjected/TipSetDef/Tips.xml
Core/Keyed/Dialogs_Various.xml
Core/Keyed/Misc_Gameplay.xml

Atualização da tradução do core para a versão 1.3.3200 do RimWorld.

RimWorld Update

---

Core/Keyed/Letters.xml

Correção de pequenos erros não vistos em revisões anteriores.

Minor Bugs Fix

---

Core/DefInjected/ConceptDef/Concepts_TriggeredModal.xml
Core/DefInjected/InstructionDef/Instructions.xml
Core/DefInjected/KeyBindingDef/KeyBindings.xml
Core/DefInjected/ThingDef/ImpliedDefs.xml
Core/Keyed/Dialogs_Various.xml
Core/Keyed/Menu_Options.xml
Core/Keyed/Menus_Main.xml
Ideology/DefInjected/ThoughtDef/Precepts_MeatEating.xml
Ideology/Keyed/Dialogs_Various.xml
Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml

Este Pull Request visa deixar a tradução de acordo com a versão mais recente do RimWorld (1.3.3326).
Também foram feitas algumas pequenas correções.

RimWorld Update 1.3.3326 + Pequenas Correções

---

Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
Ideology/DefInjected/MemeDef/Memes_GenderSupremacy.xml
Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
Ideology/DefInjected/MemeDef/Memes_Individualism.xml
Ideology/DefInjected/MemeDef/Memes_Misc.xml
Ideology/DefInjected/MemeDef/Memes_Primacy.xml
Ideology/DefInjected/MemeDef/Memes_Structures_Basic.xml
Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
Ideology/Keyed/Misc_Gameplay.xml

Apenas realiza algumas pequenas alterações de modo a melhorar a I.U..

Interface de Usuário - Ideology

---

Core/DefInjected/WorkTypeDef/WorkTypes.xml
Core/Keyed/Dialogs_Various.xml

Estou enviando apenas a correção de dois termos (indicados abaixo):
1) RimWorld-PortugueseBrazilian/Core/Keyed/Dialogs_Various.xml
Corrigindo termo "Fêmea Jovem" (linha 1135)
2) RimWorld-PortugueseBrazilian/Core/DefInjected/WorkTypeDef/WorkTypes.xml
Corrigindo termo "agricultura" (linha 97)
Solicito gentilmente a revisão/correção e aprovação desta mudança.
Obrigado!
Gostaria de uma orientação sobre como testar uma mudança de tradução na versão comercial do RimWorld (Steam). Se houver um manual de como fazê-lo, favor enviar para meu email - fred.lira@gmail.com). Desde já agradeço!
Esta é minha primeira tentativa de contribuir com este projeto.
Li a instrução de colaboração. Peço desculpas por qualquer equivoco no processo deste pull request.

Pequeno ajuste (termos: agricultura e fêmea jovem)

---

Core/Keyed/Misc_Gameplay.xml

Correção de Erro de Capitalização

---

.Instalação/ScriptDeAtualização.ps1

Altera a codificação do arquivo para UTF-8 com BOM.
Corrige #278

Codificação UTF-8 com BOM

---

Anomaly/DefInjected/BackstoryDef/Solid.xml
Anomaly/DefInjected/BiomeDef/LabyrinthMapGenerator.xml
Anomaly/DefInjected/BiomeDef/MetalHellMapGenerator.xml
Anomaly/DefInjected/BiomeDef/UndercaveMapGenerator.xml
Anomaly/DefInjected/BodyPartDef/Bodies_Entities.xml
Anomaly/DefInjected/BodyPartDef/Bodies_Fleshbeasts.xml
Anomaly/DefInjected/BodyPartGroupDef/Bodies_Entities.xml
Anomaly/DefInjected/BodyPartGroupDef/Bodies_Fleshbeasts.xml
Anomaly/DefInjected/BodyPartGroupDef/BodyPartGroups.xml
Anomaly/DefInjected/DamageDef/Damages_Environmental.xml
Anomaly/DefInjected/DamageDef/Damages_Misc.xml
Anomaly/DefInjected/DesignationCategoryDef/DesignationCategories.xml
Anomaly/DefInjected/EntityCategoryDef/EntityCategories.xml

Um batch inicial de traduções para a nova DLC.
Essa é apenas uma tradução parcial e inicial. Se quiserem aguardar um progresso maior para mesclar, não vejo problemas.

Tradução inicial para a DLC Anomaly

---

Core/Keyed/Enums.xml
Core/Keyed/Menu_Options.xml

Traduz as novas configurações da 1.5. E uns coisinho.

Tradução do Menu de Configurações da 1.5

---

.Instalação/ScriptDeAtualização.ps1
Anomaly/DefInjected/AbilityDef/Abilities.xml
Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
Anomaly/DefInjected/BodyDef/Bodies_Entities.xml
Anomaly/DefInjected/BodyDef/Bodies_Fleshbeasts.xml

Tradução da DLC Anomaly, HabilityDef/Entidades e Corpos

---

Anomaly/DefInjected/PreceptDef/Precepts_Inhumanizing.xml
Anomaly/DefInjected/PreceptDef/Precepts_PsychicRituals.xml
Anomaly/DefInjected/PreceptDef/Precepts_VoidStudy.xml
Anomaly/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionModeDefs.xml
Anomaly/DefInjected/StatDef/Stats_Containment.xml
Anomaly/DefInjected/StatDef/Stats_Pawns_Misc.xml
Anomaly/DefInjected/StatDef/Stats_PsychicRituals.xml

Tradução das pastas: ´´StatDef´´, ´´PreceptDef´´

Tradução da DLC Anomaly, StatDef, PreceptDef e PrisonerInteractionModeDef

---

Core/Keyed/Menu_Options.xml

Corrige um erro nas configurações.

Hotfix, Erro nas Configurações

---

Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
Anomaly/DefInjected/HairDef/HairsCultist.xml
Anomaly/DefInjected/HediffDef/Hediffs_BodyParts_Prosthetic.xml
Anomaly/DefInjected/HediffDef/Hediffs_Global_Misc.xml

Cabelos, próteses carnais e global

Tradução da DLC Anomaly, HairDef e HediffDef

---

Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml

 Tradução da DLC Anomaly, CreepJoinerBaseDef
